"""initial_schema

Revision ID: c9846360a0a9
Revises:
Create Date: 2026-09-02 11:17:01.479481
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


revision: str = 'c9846360a0a9'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alert_rules',
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('rule_type', sa.String(length=64), nullable=False),
    sa.Column('conditions', sa.JSON(), nullable=False),
    sa.Column('lead_times_minutes', sa.JSON(), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_alert_rules'))
    )
    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=255), nullable=False),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('entity_type', sa.String(length=100), nullable=False),
    sa.Column('entity_id', sa.Uuid(), nullable=True),
    sa.Column('request_id', sa.String(length=100), nullable=True),
    sa.Column('before', sa.JSON(), nullable=True),
    sa.Column('after', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_audit_logs'))
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_entity_created', ['entity_type', 'entity_id', 'created_at'], unique=False)

    op.create_table('events',
    sa.Column('canonical_key', sa.String(length=255), nullable=False),
    sa.Column('title_zh', sa.String(length=500), nullable=False),
    sa.Column('title_original', sa.String(length=500), nullable=True),
    sa.Column('normalized_title', sa.String(length=500), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('status', sa.Enum('confirmed', 'provisional', 'tba', 'expected', 'rescheduled', 'cancelled', 'completed', 'ignored', name='eventstatus', native_enum=False), nullable=False),
    sa.Column('importance', sa.Enum('critical', 'high', 'medium', 'low', name='importance', native_enum=False), nullable=False),
    sa.Column('date_precision', sa.Enum('minute', 'hour', 'date', 'window', 'unknown', name='dateprecision', native_enum=False), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('ends_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('original_timezone', sa.String(length=64), nullable=True),
    sa.Column('original_time_text', sa.String(length=255), nullable=True),
    sa.Column('reference_period', sa.String(length=100), nullable=True),
    sa.Column('market_tags', sa.JSON(), nullable=False),
    sa.Column('tickers', sa.JSON(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('reminder_enabled', sa.Boolean(), nullable=False),
    sa.Column('is_manual', sa.Boolean(), nullable=False),
    sa.Column('is_deleted', sa.Boolean(), nullable=False),
    sa.Column('current_version', sa.Integer(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.CheckConstraint("(date_precision IN ('minute','hour','window') AND starts_at IS NOT NULL) OR (date_precision = 'date' AND local_date IS NOT NULL AND starts_at IS NULL) OR (date_precision = 'unknown')", name=op.f('ck_events_valid_time_precision')),
    sa.CheckConstraint("date_precision != 'window' OR ends_at IS NOT NULL", name=op.f('ck_events_window_has_end')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_events')),
    sa.UniqueConstraint('canonical_key', name=op.f('uq_events_canonical_key'))
    )
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_events_category'), ['category'], unique=False)
        batch_op.create_index('ix_events_country_category', ['country_code', 'category'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_event_type'), ['event_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_importance'), ['importance'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_deleted'), ['is_deleted'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_is_manual'), ['is_manual'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_local_date'), ['local_date'], unique=False)
        batch_op.create_index('ix_events_local_date_importance', ['local_date', 'importance'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_normalized_title'), ['normalized_title'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_starts_at'), ['starts_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_events_status'), ['status'], unique=False)
        batch_op.create_index('ix_events_time_range', ['starts_at', 'ends_at'], unique=False)

    op.create_table('sources',
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('country_code', sa.String(length=8), nullable=False),
    sa.Column('official_url', sa.Text(), nullable=False),
    sa.Column('source_type', sa.String(length=32), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('health', sa.Enum('healthy', 'stale', 'degraded', 'failed', 'disabled', name='sourcehealth', native_enum=False), nullable=False),
    sa.Column('schedule', sa.String(length=100), nullable=False),
    sa.Column('stale_after_hours', sa.Integer(), nullable=False),
    sa.Column('consecutive_failures', sa.Integer(), nullable=False),
    sa.Column('last_success_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_failure_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_event_count', sa.Integer(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_sources')),
    sa.UniqueConstraint('key', name=op.f('uq_sources_key'))
    )
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sources_country_code'), ['country_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_sources_health'), ['health'], unique=False)

    op.create_table('worker_heartbeats',
    sa.Column('worker_name', sa.String(length=100), nullable=False),
    sa.Column('heartbeat_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('metadata_json', sa.JSON(), nullable=False),
    sa.PrimaryKeyConstraint('worker_name', name=op.f('pk_worker_heartbeats'))
    )
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_worker_heartbeats_heartbeat_at'), ['heartbeat_at'], unique=False)

    op.create_table('event_changes',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('from_version', sa.Integer(), nullable=True),
    sa.Column('to_version', sa.Integer(), nullable=False),
    sa.Column('change_type', sa.String(length=64), nullable=False),
    sa.Column('changed_fields', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_changes_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_changes'))
    )
    with op.batch_alter_table('event_changes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_event_changes_change_type'), ['change_type'], unique=False)
        batch_op.create_index('ix_event_changes_created', ['created_at'], unique=False)

    op.create_table('event_field_locks',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('field_name', sa.String(length=100), nullable=False),
    sa.Column('locked_by', sa.String(length=255), nullable=False),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_field_locks_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_field_locks')),
    sa.UniqueConstraint('event_id', 'field_name', name=op.f('uq_event_field_locks_event_id'))
    )
    op.create_table('event_versions',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('snapshot', sa.JSON(), nullable=False),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('actor_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_versions_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_versions')),
    sa.UniqueConstraint('event_id', 'version', name=op.f('uq_event_versions_event_id'))
    )
    op.create_table('fetch_runs',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('run_key', sa.String(length=255), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'succeeded', 'failed', 'partial', name='runstatus', native_enum=False), nullable=False),
    sa.Column('adapter_version', sa.String(length=50), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('fetched_count', sa.Integer(), nullable=False),
    sa.Column('parsed_count', sa.Integer(), nullable=False),
    sa.Column('created_count', sa.Integer(), nullable=False),
    sa.Column('updated_count', sa.Integer(), nullable=False),
    sa.Column('error_type', sa.String(length=100), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_fetch_runs_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_fetch_runs')),
    sa.UniqueConstraint('run_key', name=op.f('uq_fetch_runs_run_key'))
    )
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.create_index('ix_fetch_runs_source_started', ['source_id', 'started_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_fetch_runs_status'), ['status'], unique=False)

    op.create_table('notifications',
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('alert_rule_id', sa.Uuid(), nullable=True),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('alert_type', sa.String(length=64), nullable=False),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('event_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'sending', 'sent', 'failed', 'cancelled', name='notificationstatus', native_enum=False), nullable=False),
    sa.Column('attempts', sa.Integer(), nullable=False),
    sa.Column('next_attempt_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sent_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['alert_rule_id'], ['alert_rules.id'], name=op.f('fk_notifications_alert_rule_id_alert_rules'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_notifications_event_id_events'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_notifications')),
    sa.UniqueConstraint('channel', 'event_id', 'alert_type', 'scheduled_at', 'event_version', name='uq_notification_delivery')
    )
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.create_index('ix_notifications_due', ['status', 'scheduled_at'], unique=False)

    op.create_table('raw_snapshots',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('fetch_run_id', sa.Uuid(), nullable=False),
    sa.Column('url', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('content_type', sa.String(length=100), nullable=False),
    sa.Column('body', sa.LargeBinary(), nullable=False),
    sa.Column('http_status', sa.Integer(), nullable=False),
    sa.Column('adapter_version', sa.String(length=50), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['fetch_runs.id'], name=op.f('fk_raw_snapshots_fetch_run_id_fetch_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_raw_snapshots_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_raw_snapshots')),
    sa.UniqueConstraint('source_id', 'content_hash', name=op.f('uq_raw_snapshots_source_id'))
    )
    with op.batch_alter_table('raw_snapshots', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_raw_snapshots_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_raw_snapshots_expires_at'), ['expires_at'], unique=False)

    op.create_table('source_observations',
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('fetch_run_id', sa.Uuid(), nullable=False),
    sa.Column('snapshot_id', sa.Uuid(), nullable=False),
    sa.Column('event_id', sa.Uuid(), nullable=True),
    sa.Column('source_event_id', sa.String(length=255), nullable=False),
    sa.Column('fingerprint', sa.String(length=64), nullable=False),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('institution', sa.String(length=255), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('starts_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('local_date', sa.Date(), nullable=True),
    sa.Column('original_payload', sa.JSON(), nullable=False),
    sa.Column('match_confidence', sa.Float(), nullable=True),
    sa.Column('match_reason', sa.Text(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_source_observations_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['fetch_run_id'], ['fetch_runs.id'], name=op.f('fk_source_observations_fetch_run_id_fetch_runs'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['snapshot_id'], ['raw_snapshots.id'], name=op.f('fk_source_observations_snapshot_id_raw_snapshots'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_source_observations_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_source_observations')),
    sa.UniqueConstraint('source_id', 'source_event_id', name=op.f('uq_source_observations_source_id'))
    )
    with op.batch_alter_table('source_observations', schema=None) as batch_op:
        batch_op.create_index('ix_observations_event_date', ['event_type', 'local_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_source_observations_fingerprint'), ['fingerprint'], unique=False)

    op.create_table('event_sources',
    sa.Column('event_id', sa.Uuid(), nullable=False),
    sa.Column('source_id', sa.Uuid(), nullable=False),
    sa.Column('observation_id', sa.Uuid(), nullable=True),
    sa.Column('is_primary', sa.Boolean(), nullable=False),
    sa.Column('last_verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['events.id'], name=op.f('fk_event_sources_event_id_events'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['observation_id'], ['source_observations.id'], name=op.f('fk_event_sources_observation_id_source_observations'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['source_id'], ['sources.id'], name=op.f('fk_event_sources_source_id_sources'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_sources')),
    sa.UniqueConstraint('event_id', 'source_id', 'observation_id', name=op.f('uq_event_sources_event_id'))
    )
    op.create_table('review_queue',
    sa.Column('observation_id', sa.Uuid(), nullable=False),
    sa.Column('candidate_event_id', sa.Uuid(), nullable=True),
    sa.Column('status', sa.Enum('pending', 'approved', 'ignored', 'merged', name='reviewstatus', native_enum=False), nullable=False),
    sa.Column('reason', sa.Text(), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=True),
    sa.Column('resolution', sa.JSON(), nullable=True),
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['candidate_event_id'], ['events.id'], name=op.f('fk_review_queue_candidate_event_id_events'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['observation_id'], ['source_observations.id'], name=op.f('fk_review_queue_observation_id_source_observations'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_review_queue'))
    )
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.create_index('ix_review_status_created', ['status', 'created_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review_queue', schema=None) as batch_op:
        batch_op.drop_index('ix_review_status_created')

    op.drop_table('review_queue')
    op.drop_table('event_sources')
    with op.batch_alter_table('source_observations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_source_observations_fingerprint'))
        batch_op.drop_index('ix_observations_event_date')

    op.drop_table('source_observations')
    with op.batch_alter_table('raw_snapshots', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_raw_snapshots_expires_at'))
        batch_op.drop_index(batch_op.f('ix_raw_snapshots_content_hash'))

    op.drop_table('raw_snapshots')
    with op.batch_alter_table('notifications', schema=None) as batch_op:
        batch_op.drop_index('ix_notifications_due')

    op.drop_table('notifications')
    with op.batch_alter_table('fetch_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_fetch_runs_status'))
        batch_op.drop_index('ix_fetch_runs_source_started')

    op.drop_table('fetch_runs')
    op.drop_table('event_versions')
    op.drop_table('event_field_locks')
    with op.batch_alter_table('event_changes', schema=None) as batch_op:
        batch_op.drop_index('ix_event_changes_created')
        batch_op.drop_index(batch_op.f('ix_event_changes_change_type'))

    op.drop_table('event_changes')
    with op.batch_alter_table('worker_heartbeats', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_worker_heartbeats_heartbeat_at'))

    op.drop_table('worker_heartbeats')
    with op.batch_alter_table('sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sources_health'))
        batch_op.drop_index(batch_op.f('ix_sources_country_code'))

    op.drop_table('sources')
    with op.batch_alter_table('events', schema=None) as batch_op:
        batch_op.drop_index('ix_events_time_range')
        batch_op.drop_index(batch_op.f('ix_events_status'))
        batch_op.drop_index(batch_op.f('ix_events_starts_at'))
        batch_op.drop_index(batch_op.f('ix_events_normalized_title'))
        batch_op.drop_index('ix_events_local_date_importance')
        batch_op.drop_index(batch_op.f('ix_events_local_date'))
        batch_op.drop_index(batch_op.f('ix_events_is_manual'))
        batch_op.drop_index(batch_op.f('ix_events_is_deleted'))
        batch_op.drop_index(batch_op.f('ix_events_importance'))
        batch_op.drop_index(batch_op.f('ix_events_event_type'))
        batch_op.drop_index(batch_op.f('ix_events_country_code'))
        batch_op.drop_index('ix_events_country_category')
        batch_op.drop_index(batch_op.f('ix_events_category'))

    op.drop_table('events')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_entity_created')

    op.drop_table('audit_logs')
    op.drop_table('alert_rules')
    # ### end Alembic commands ###
